language: java
jdk: openjdk8

env:
  - DOSSIER_LIVRAISON_CIBLE="TestTravis"     PATH_LIVRAISON_CIBLE="~/Production_apps/Prod_Apps/$DOSSIER_LIVRAISON_CIBLE"     PROJECT_FOLDER_NAME="test"     PATH_DEPLOYMENT_FILE="./deploy.sh"    TRAVIS_DEPLOYMENT_GITHUB_URL="https://raw.githubusercontent.com/Rayanox/TravisDeployment/master/deploy.sh"

addons:
  apt:
    packages:
    - putty-tools
    - sshpass
    - plink

script:
  - echo " -> ls"
  - ls

deploy:
  provider: script
  cleanup: true
  # on:
    # tags: true
  script: >-
    cd $PROJECT_FOLDER_NAME
    && mvn clean package
    && cd target
    && jarName=`ls *.jar`

    && deploymentCible=$PATH_LIVRAISON_CIBLE
    && echo "deploymentCible = $deploymentCible"
    && echo "PATH_LIVRAISON_CIBLE = $PATH_LIVRAISON_CIBLE"

       # Import du script de deploiement sur le serveur + remplacement des arguments du script
    && curl -o $PATH_DEPLOYMENT_FILE $TRAVIS_DEPLOYMENT_GITHUB_URL
    && sed -i "s/\$argument1/$jarName/" $PATH_DEPLOYMENT_FILE
    && sed -i "s#\$argument2#$PATH_LIVRAISON_CIBLE#" $PATH_DEPLOYMENT_FILE

       # ------- SERVER SIDE ----------

    && sshpass -p "$PASSWORD_MY_SERVER" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $LOGIN_MY_SERVER@$IP_MY_SERVER "rm -f $PATH_LIVRAISON_CIBLE/*.jar"
    && sshpass -p "$PASSWORD_MY_SERVER" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./$jarName $LOGIN_MY_SERVER@$IP_MY_SERVER:$PATH_LIVRAISON_CIBLE

    && echo y | plink -ssh $LOGIN_MY_SERVER@$IP_MY_SERVER -pw $PASSWORD_MY_SERVER -m ./$PATH_DEPLOYMENT_FILE

