language: java
jdk: openjdk8

env:
  - DOSSIER_LIVRAISON_CIBLE="TestTravis"     PATH_LIVRAISON_CIBLE="~/Production_apps/Prod_Apps/$DOSSIER_LIVRAISON_CIBLE"     PROJECT_FOLDER_NAME="test"     PATH_DEPLOYMENT_FILE="./deploy.sh"    TRAVIS_DEPLOYMENT_GITHUB_URL="https://raw.githubusercontent.com/Rayanox/TravisDeployment/master/deploy.sh"

addons:
  apt:
    packages:
    - putty-tools
    - sshpass
    - plink

script:
  - echo " -> ls"
  - ls

deploy:
  provider: script
  cleanup: true
  # on:
    # tags: true
  script: >-
    echo "testRayane" > BIBI.txt
    && ls -l
    && cat BIBI.txt

